### ISSUE TITLE
Bug Report: app version 0.5.23 does not start

### ISSUE THREAD

**Issue by FadeMind** [Timthreetwelve/WUView#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues and have read the Known Issues and Troubleshooting topics in the Wiki

### What happened or didn't happen

App window does not show up. 

### Steps To Reproduce

1. Install 0.5.23.
2. Launch app.
3. Nothing happen.

### Version

0.5.23

### Windows Version

Windows 11  22H2 22621.2361

### Anything else?

<32Bit>
2.0.50727.9174
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.8.9181.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.9174
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.8.9181.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

==== Installed .NET Frameworks ====
.NET FW 2.0 SP 2 (CLR 2.0)
.NET FW 3.0 SP 2 (CLR 2.0)
.NET FW 3.5 SP 1 (CLR 2.0)
.NET FW 4.6.2 Windows 11 22H2(CLR 4.0)
.NET FW 4.7 Windows 11 22H2(CLR 4.0)
.NET FW 4.7.1 Windows 11 22H2(CLR 4.0)
.NET FW 4.7.2 Windows 11 22H2(CLR 4.0)
.NET FW 4.8 Windows 11 22H2(CLR 4.0)
.NET FW 4.8.1 Windows 11 22H2(CLR 4.0)

==== Installed .NET Core Runtime 64bit ====
Microsoft.AspNetCore.App 7.0.11
Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29
Microsoft.NETCore.App 6.0.22
Microsoft.NETCore.App 7.0.11
Microsoft.NETCore.App 8.0.0-rc.1.23419.4
Microsoft.WindowsDesktop.App 6.0.22
Microsoft.WindowsDesktop.App 7.0.11
Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5

==== Installed .NET Core Runtime 32bit ====
Microsoft.NETCore.App 6.0.22
Microsoft.NETCore.App 7.0.11
Microsoft.NETCore.App 8.0.0-rc.1.23419.4
Microsoft.WindowsDesktop.App 6.0.22
Microsoft.WindowsDesktop.App 7.0.11
Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5

==== Installed .NET Core Sdk 64bit ====

==== Installed .NET Core Sdk 32bit ====

==== Languages ====
< Installed Languages 3.0>
English - United States
Polish
< Installed Languages 3.5.x>
English - United States
Polish
< Installed Languages 4.x>
English - United States
Polish

==== Updates ====
Microsoft .NET Framework 4 Client Profile 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Extended 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
==== END REPORT ====

**Comment by Timthreetwelve** [comment]
@FadeMind, I'm sorry that it's not working for you. Let's see if we can fix the problem.

Your description says:

> Install 0.5.23.
> Launch app.
> Nothing happen.

Then I'll assume that the installation went okay, and the app just won't start. If that isn't correct, please let me know.

If you could attach a copy of the log file that would help a lot. It should be in the Temp directory in a folder named T_K. The filename will be WUView._yyyymmdd_.log, where yyymmdd is the date. For example `"D:\Temp\T_K\WUView.20230930.log"`

Thanks,
Tim

**Comment by FadeMind** [comment]
I don't have these log. Portable version does not create any log file. 
Setup version create classic install log file **Setup_Log.txt**
```
2023-10-01 08:11:55.915   Log opened. (Time zone: UTC+02:00)
2023-10-01 08:11:55.915   Setup version: Inno Setup version 6.2.2
2023-10-01 08:11:55.915   Original Setup EXE: D:\fademind\Downloads\Programs\WindowsUpdateViewer_0.5.23.0_Setup.exe
2023-10-01 08:11:55.915   Setup command line: /SL5="$D0B64,3620967,887296,D:\fademind\Downloads\Programs\WindowsUpdateViewer_0.5.23.0_Setup.exe" 
2023-10-01 08:11:55.915   Windows version: 10.0.22631  (NT platform: Yes)
2023-10-01 08:11:55.915   64-bit Windows: Yes
2023-10-01 08:11:55.915   Processor architecture: x64
2023-10-01 08:11:55.915   User privileges: None
2023-10-01 08:11:55.915   Administrative install mode: No
2023-10-01 08:11:55.915   Install mode root key: HKEY_CURRENT_USER
2023-10-01 08:11:55.915   64-bit install mode: No
2023-10-01 08:11:58.776   Created temporary directory: C:\Users\fademind\AppData\Local\Temp\is-9M2RH.tmp
2023-10-01 08:12:01.309   Found 8 files to register with RestartManager.
2023-10-01 08:12:01.309   Calling RestartManager's RmGetList.
2023-10-01 08:12:01.309   RmGetList finished successfully.
2023-10-01 08:12:01.309   RestartManager found no applications using one of our files.
2023-10-01 08:12:01.324   Starting the installation process.
2023-10-01 08:12:01.324   Creating directory: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer
2023-10-01 08:12:01.324   Directory for uninstall files: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer
2023-10-01 08:12:01.324   Creating new uninstall log: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\unins000.dat
2023-10-01 08:12:01.324   -- File entry --
2023-10-01 08:12:01.324   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\unins000.exe
2023-10-01 08:12:01.324   Time stamp of our file: 2023-10-01 08:11:55.685
2023-10-01 08:12:01.324   Installing the file.
2023-10-01 08:12:01.324   Successfully installed the file.
2023-10-01 08:12:01.324   -- File entry --
2023-10-01 08:12:01.340   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\WUView.exe
2023-10-01 08:12:01.340   Time stamp of our file: 2023-09-27 16:45:30.000
2023-10-01 08:12:01.340   Installing the file.
2023-10-01 08:12:01.340   Successfully installed the file.
2023-10-01 08:12:01.340   -- File entry --
2023-10-01 08:12:01.340   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\CommunityToolkit.Mvvm.dll
2023-10-01 08:12:01.340   Time stamp of our file: 2023-07-05 13:52:50.000
2023-10-01 08:12:01.340   Installing the file.
2023-10-01 08:12:01.340   Successfully installed the file.
2023-10-01 08:12:01.340   -- File entry --
2023-10-01 08:12:01.340   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\MaterialDesignColors.dll
2023-10-01 08:12:01.340   Time stamp of our file: 2023-05-11 09:46:58.000
2023-10-01 08:12:01.340   Installing the file.
2023-10-01 08:12:01.340   Successfully installed the file.
2023-10-01 08:12:01.340   -- File entry --
2023-10-01 08:12:01.355   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\MaterialDesignThemes.Wpf.dll
2023-10-01 08:12:01.355   Time stamp of our file: 2023-05-11 09:47:12.000
2023-10-01 08:12:01.355   Installing the file.
2023-10-01 08:12:01.496   Successfully installed the file.
2023-10-01 08:12:01.496   -- File entry --
2023-10-01 08:12:01.496   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\Microsoft.Xaml.Behaviors.dll
2023-10-01 08:12:01.496   Time stamp of our file: 2021-11-18 01:31:02.000
2023-10-01 08:12:01.496   Installing the file.
2023-10-01 08:12:01.496   Successfully installed the file.
2023-10-01 08:12:01.496   -- File entry --
2023-10-01 08:12:01.496   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\NLog.dll
2023-10-01 08:12:01.496   Time stamp of our file: 2023-09-06 13:34:18.000
2023-10-01 08:12:01.496   Installing the file.
2023-10-01 08:12:01.512   Successfully installed the file.
2023-10-01 08:12:01.512   -- File entry --
2023-10-01 08:12:01.512   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\Octokit.dll
2023-10-01 08:12:01.527   Time stamp of our file: 2023-09-22 18:41:28.000
2023-10-01 08:12:01.527   Installing the file.
2023-10-01 08:12:01.543   Successfully installed the file.
2023-10-01 08:12:01.543   -- File entry --
2023-10-01 08:12:01.543   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\WUView.dll
2023-10-01 08:12:01.543   Time stamp of our file: 2023-09-27 16:45:30.000
2023-10-01 08:12:01.543   Installing the file.
2023-10-01 08:12:01.559   Successfully installed the file.
2023-10-01 08:12:01.559   -- File entry --
2023-10-01 08:12:01.559   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\WUView.deps.json
2023-10-01 08:12:01.559   Time stamp of our file: 2023-09-27 16:45:30.000
2023-10-01 08:12:01.559   Installing the file.
2023-10-01 08:12:01.559   Successfully installed the file.
2023-10-01 08:12:01.559   -- File entry --
2023-10-01 08:12:01.559   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\WUView.runtimeconfig.json
2023-10-01 08:12:01.559   Time stamp of our file: 2023-09-27 16:42:40.000
2023-10-01 08:12:01.559   Installing the file.
2023-10-01 08:12:01.559   Successfully installed the file.
2023-10-01 08:12:01.559   -- File entry --
2023-10-01 08:12:01.559   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\ReadMe.txt
2023-10-01 08:12:01.559   Time stamp of our file: 2023-09-15 13:09:44.000
2023-10-01 08:12:01.559   Installing the file.
2023-10-01 08:12:01.559   Successfully installed the file.
2023-10-01 08:12:01.559   -- File entry --
2023-10-01 08:12:01.559   Dest filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\License.txt
2023-10-01 08:12:01.559   Time stamp of our file: 2023-04-24 19:20:18.000
2023-10-01 08:12:01.559   Installing the file.
2023-10-01 08:12:01.559   Successfully installed the file.
2023-10-01 08:12:01.559   -- Icon entry --
2023-10-01 08:12:01.559   Dest filename: C:\Users\fademind\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Windows Update Viewer.lnk
2023-10-01 08:12:01.559   Creating the icon.
2023-10-01 08:12:01.590   Successfully created the icon.
2023-10-01 08:12:01.590   -- Registry entry --
2023-10-01 08:12:01.590   Key: HKEY_CURRENT_USER\Software\T_K
2023-10-01 08:12:01.590   Creating or opening the key.
2023-10-01 08:12:01.590   Successfully created the key.
2023-10-01 08:12:01.590   -- Registry entry --
2023-10-01 08:12:01.590   Key: HKEY_CURRENT_USER\Software\T_K\Windows Update Viewer
2023-10-01 08:12:01.590   Creating or opening the key.
2023-10-01 08:12:01.590   Successfully created the key.
2023-10-01 08:12:01.590   -- Registry entry --
2023-10-01 08:12:01.590   Key: HKEY_CURRENT_USER\Software\T_K\Windows Update Viewer
2023-10-01 08:12:01.590   Value name: Copyright
2023-10-01 08:12:01.590   Creating or opening the key.
2023-10-01 08:12:01.590   Creating or setting the value.
2023-10-01 08:12:01.590   Successfully created or set the value.
2023-10-01 08:12:01.590   -- Registry entry --
2023-10-01 08:12:01.590   Key: HKEY_CURRENT_USER\Software\T_K\Windows Update Viewer
2023-10-01 08:12:01.590   Value name: Install Date
2023-10-01 08:12:01.590   Creating or opening the key.
2023-10-01 08:12:01.590   Creating or setting the value.
2023-10-01 08:12:01.590   Successfully created or set the value.
2023-10-01 08:12:01.590   -- Registry entry --
2023-10-01 08:12:01.590   Key: HKEY_CURRENT_USER\Software\T_K\Windows Update Viewer
2023-10-01 08:12:01.590   Value name: Version
2023-10-01 08:12:01.590   Creating or opening the key.
2023-10-01 08:12:01.590   Creating or setting the value.
2023-10-01 08:12:01.590   Successfully created or set the value.
2023-10-01 08:12:01.590   -- Registry entry --
2023-10-01 08:12:01.590   Key: HKEY_CURRENT_USER\Software\T_K\Windows Update Viewer
2023-10-01 08:12:01.590   Value name: Install Folder
2023-10-01 08:12:01.590   Creating or opening the key.
2023-10-01 08:12:01.590   Creating or setting the value.
2023-10-01 08:12:01.590   Successfully created or set the value.
2023-10-01 08:12:01.590   -- Registry entry --
2023-10-01 08:12:01.590   Key: HKEY_CURRENT_USER\Software\T_K\Windows Update Viewer
2023-10-01 08:12:01.590   Value name: Installer Language
2023-10-01 08:12:01.590   Creating or opening the key.
2023-10-01 08:12:01.590   Creating or setting the value.
2023-10-01 08:12:01.590   Successfully created or set the value.
2023-10-01 08:12:01.590   -- Registry entry --
2023-10-01 08:12:01.590   Key: HKEY_CURRENT_USER\Software\T_K\Windows Update Viewer
2023-10-01 08:12:01.590   Value name: Edition
2023-10-01 08:12:01.590   Deleting the value.
2023-10-01 08:12:01.590   Successfully deleted the value.
2023-10-01 08:12:01.590   Saving uninstall information.
2023-10-01 08:12:01.590   Creating new uninstall key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\{3A152885-8378-4FDE-AFCC-85D096B16A1D}_is1
2023-10-01 08:12:01.590   Writing uninstall key values.
2023-10-01 08:12:01.605   Detected previous administrative 32-bit install? No
2023-10-01 08:12:01.605   Detected previous administrative 64-bit install? No
2023-10-01 08:12:01.605   Installation process succeeded.
2023-10-01 08:12:01.605   Need to restart Windows? No
2023-10-01 08:12:04.796   -- Run entry --
2023-10-01 08:12:04.796   Run as: Original user
2023-10-01 08:12:04.796   Type: ShellExec
2023-10-01 08:12:04.796   Filename: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\WUView.exe
2023-10-01 08:12:05.838   Setup log file copied to: C:\Users\fademind\AppData\Local\Programs\T_K\Windows Update Viewer\Setup_Log.txt

```

**Comment by Timthreetwelve** [comment]
Thanks for the Setup log. It appears to have installed successfully.

Since you can't find the application's log file it will be necessary to try to find some clues in the Event Viewer. In the Event Viewer select Application under Windows Logs, then look for` .NET Runtime `in the source column. Or you can select Create Custom View (right side) and select the options so that it looks like this.
![258214180-54deaebe-abf6-439f-9f8e-ed12ff023220](https://github.com/Timthreetwelve/WUView/assets/43152358/556bcd29-c899-485b-9f95-831922f4ac9c)
Then try to find the entry for WUView in the top line in the General pane. If you are successful in locating the event, copy the text in the General pane a paste or attach it to this issue. If there are a lot of entries, you might try limiting it to Event ID 1026, but I can't be 100% of the Event ID in your case.
![258218112-198aac1b-332a-4fb1-8986-608ec28a9616](https://github.com/Timthreetwelve/WUView/assets/43152358/c095aff8-1dcc-4574-ae82-f9ab0d1e236c)

**Comment by FadeMind** [comment]
![20231001-1696174297](https://github.com/Timthreetwelve/WUView/assets/9846948/15f852ba-3930-4df2-82be-81e6943c2add)

```
Application: WUView.exe
CoreCLR Version: 6.0.2223.42425
.NET Version: 6.0.22
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at WUView.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at WUView.App.Main()
```

![20231001-1696174397](https://github.com/Timthreetwelve/WUView/assets/9846948/3c133b23-b064-4c9a-8207-046bd4610006)


```
Name of the application causing the error: WUView.exe, version: 0.5.23.0, time signature: 0x64e81669
Name of the module causing the error: KERNELBASE.dll, version: 10.0.22621.2361, time signature: 0xc0c1b229
Exception code: 0xe0434352
Error offset: 0x0000000000064ffc
ID of the process causing the error: 0x0x2FF8
Start time of the application causing the error: 0x0x1D9F47C2BF58232
Path of the application causing the error: 
Path of the module causing the error: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 12e24cef-cffd-4150-810b-49c782ed8102
Full name of the package causing the error: 
Application ID relative to the package causing the error: 

```

**Comment by Timthreetwelve** [comment]
This has me stumped. It is crashing in the startup process before the application code starts. That's why there isn't a log file. 

In Event Viewer are there any other messages that have the same time stamp (or very close) as the error message from WUView?

**Comment by FadeMind** [comment]
@Timthreetwelve 
![20231001-1696180586](https://github.com/Timthreetwelve/WUView/assets/9846948/bbecd836-7f9c-4c5c-bfb2-e7b46d796ef9)
![20231001-1696180578](https://github.com/Timthreetwelve/WUView/assets/9846948/f4f7e6ba-89ae-4299-8548-cd04743b3abe)
![20231001-1696180540](https://github.com/Timthreetwelve/WUView/assets/9846948/f1a38c05-12a9-4b2c-8c65-ef5856d721d5)
![20231001-1696180527](https://github.com/Timthreetwelve/WUView/assets/9846948/f542828d-8e44-4c0e-a3f0-b48350c98b59)
![20231001-1696180314](https://github.com/Timthreetwelve/WUView/assets/9846948/0cee5cda-3838-4b48-91d4-9f5cfc6cdf61)

**Comment by FadeMind** [comment]
@Timthreetwelve 
5.23 does not start. 
Older versions works well

![20231001-1696184898](https://github.com/Timthreetwelve/WUView/assets/9846948/56a8c2de-96f7-4175-aee8-f20ce97251a7)
![20231001-1696184885](https://github.com/Timthreetwelve/WUView/assets/9846948/2f5dea2c-6e35-42e9-aee7-1e45b2f90e41)
![20231001-1696184788](https://github.com/Timthreetwelve/WUView/assets/9846948/e03e85d5-9cf9-4ecc-88f7-217aabe4dce1)

**Comment by Timthreetwelve** [comment]
Thanks. That narrows it down.

Thank you for your patience!

**Comment by FadeMind** [comment]
@Timthreetwelve If you need additional debug let me know.

**Comment by Timthreetwelve** [comment]
Would you attach or paste the settings file? `Ctrl + Shift + S ` should open it. If not, it is in `C:\Users\<user>\AppData\Local\Programs\T_K\Windows Update Viewer\usersettings.json`

I think the problem might be due to a change I made to the default value of the `UseOSLanguage` setting.

**Comment by FadeMind** [comment]
Got it.
After copy `usersettings.json` from older version to dir app (portable here) launch well
diff

usersettings.json - 0.5.23.0 - NOT WORKING
usersettings.json.bak - 0.5.22.0 - WORKING


![20231001-1696186253](https://github.com/Timthreetwelve/WUView/assets/9846948/3c9e7268-a722-4da1-a076-98dbb403ad5e)

**Comment by FadeMind** [comment]
@Timthreetwelve 

`"UseOSLanguage": true,`

crashing the app.

Set `"UseOSLanguage": false,` resolved issue.

**Comment by Timthreetwelve** [comment]
Thanks, it looks like I need to revert that setting.

Am I correct that Polish is the OS language?

**Comment by FadeMind** [comment]
@Timthreetwelve Yes. Polish language.

**Comment by Timthreetwelve** [comment]
Great! Would you be willing to contribute a translation, or check the one that I have started? Google translate is good but not perfect.

**Comment by Timthreetwelve** [comment]
No pressure. If you don't want to that's fine. You've already provided a great deal of help resolving this issue.

**Comment by FadeMind** [comment]
@Timthreetwelve I will prepare xaml file and create PR. Google Translate does not care about valid variation of words. The Polish language is a nightmare for foreigners.

**Comment by Timthreetwelve** [comment]
Thank you very much! I always assume that English, especially American English, is a nightmare!

**Comment by FadeMind** [comment]
@Timthreetwelve 


![20231001-1696187685](https://github.com/Timthreetwelve/WUView/assets/9846948/6944ad18-d9f3-40ee-b137-87a7b8dbbd26)

lets play the game 🤡

gra - game
grać - play
grań - ridge


![1537530952_zgvu7d_600](https://github.com/Timthreetwelve/WUView/assets/9846948/68b0bf4b-e0b0-4dfc-8954-bc77a9291c21)

**Comment by Timthreetwelve** [comment]
![AA1hwHIW](https://github.com/Timthreetwelve/WUView/assets/43152358/5cddd177-fdb0-42c5-96f3-8f67bddd5297)

**Comment by Timthreetwelve** [comment]
@FadeMind, I was able to find the line of code that was causing the problem and was able to recreate the crash that you experienced.  I've added additional logic to catch the problem and feel confident that it won't happen again.

Thanks once again for all your time and effort. I really appreciate it. 

Tim
